apiVersion: v1
kind: Secret
metadata:
  name: shoptik-db-secrets
  namespace: shoptik
  labels:
    app.kubernetes.io/name: shoptik
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: shoptik
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: shoptik
  POSTGRES_PASSWORD: admin123
  POSTGRES_DB: shoptik_db
  
  # MongoDB
  MONGO_USER: admin
  MONGO_PASSWORD: admin123
  MONGO_DB: shoptik
  
  # Redis
  REDIS_PASSWORD: admin123
