apiVersion: v1
kind: Secret
metadata:
  name: shoptik-db-secrets
  namespace: shoptik
  labels:
    app.kubernetes.io/name: shoptik
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: shoptik
type: Opaque
stringData:
  # PostgreSQL
  postgres-username: shoptik
  postgres-password: admin123
  postgres-database: shoptik_db
  
  # MongoDB
  mongo-root-username: admin
  mongo-root-password: admin123
  mongo-database: shoptik
  
  # Redis
  redis-password: admin123
