apiVersion: v1
kind: ConfigMap
metadata:
  name: nestjs-config
  namespace: shoptik
  labels:
    app.kubernetes.io/name: nestjs-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: shoptik
data:
  NODE_ENV: "production"
  PORT: "5001"
  CORS_ORIGINS: "http://localhost:3000,https://yourdomain.com"
  GRPC_SERVICE_URL: "go-service:5003"
