// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: delivery_zone.proto

package shoptik

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeliveryZoneService_CreateDeliveryZone_FullMethodName       = "/shoptik.DeliveryZoneService/CreateDeliveryZone"
	DeliveryZoneService_GetDeliveryZone_FullMethodName          = "/shoptik.DeliveryZoneService/GetDeliveryZone"
	DeliveryZoneService_GetDeliveryZoneByPincode_FullMethodName = "/shoptik.DeliveryZoneService/GetDeliveryZoneByPincode"
	DeliveryZoneService_ListDeliveryZones_FullMethodName        = "/shoptik.DeliveryZoneService/ListDeliveryZones"
	DeliveryZoneService_UpdateDeliveryZone_FullMethodName       = "/shoptik.DeliveryZoneService/UpdateDeliveryZone"
	DeliveryZoneService_DeleteDeliveryZone_FullMethodName       = "/shoptik.DeliveryZoneService/DeleteDeliveryZone"
)

// DeliveryZoneServiceClient is the client API for DeliveryZoneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeliveryZoneService provides CRUD operations for delivery zones
type DeliveryZoneServiceClient interface {
	// Create a new delivery zone
	CreateDeliveryZone(ctx context.Context, in *CreateDeliveryZoneRequest, opts ...grpc.CallOption) (*CreateDeliveryZoneResponse, error)
	// Get a delivery zone by ID
	GetDeliveryZone(ctx context.Context, in *GetDeliveryZoneRequest, opts ...grpc.CallOption) (*GetDeliveryZoneResponse, error)
	// Get a delivery zone by pincode
	GetDeliveryZoneByPincode(ctx context.Context, in *GetDeliveryZoneByPincodeRequest, opts ...grpc.CallOption) (*GetDeliveryZoneResponse, error)
	// List all delivery zones with pagination
	ListDeliveryZones(ctx context.Context, in *ListDeliveryZonesRequest, opts ...grpc.CallOption) (*ListDeliveryZonesResponse, error)
	// Update a delivery zone
	UpdateDeliveryZone(ctx context.Context, in *UpdateDeliveryZoneRequest, opts ...grpc.CallOption) (*UpdateDeliveryZoneResponse, error)
	// Delete a delivery zone
	DeleteDeliveryZone(ctx context.Context, in *DeleteDeliveryZoneRequest, opts ...grpc.CallOption) (*DeleteDeliveryZoneResponse, error)
}

type deliveryZoneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeliveryZoneServiceClient(cc grpc.ClientConnInterface) DeliveryZoneServiceClient {
	return &deliveryZoneServiceClient{cc}
}

func (c *deliveryZoneServiceClient) CreateDeliveryZone(ctx context.Context, in *CreateDeliveryZoneRequest, opts ...grpc.CallOption) (*CreateDeliveryZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDeliveryZoneResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_CreateDeliveryZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryZoneServiceClient) GetDeliveryZone(ctx context.Context, in *GetDeliveryZoneRequest, opts ...grpc.CallOption) (*GetDeliveryZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryZoneResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_GetDeliveryZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryZoneServiceClient) GetDeliveryZoneByPincode(ctx context.Context, in *GetDeliveryZoneByPincodeRequest, opts ...grpc.CallOption) (*GetDeliveryZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeliveryZoneResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_GetDeliveryZoneByPincode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryZoneServiceClient) ListDeliveryZones(ctx context.Context, in *ListDeliveryZonesRequest, opts ...grpc.CallOption) (*ListDeliveryZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeliveryZonesResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_ListDeliveryZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryZoneServiceClient) UpdateDeliveryZone(ctx context.Context, in *UpdateDeliveryZoneRequest, opts ...grpc.CallOption) (*UpdateDeliveryZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDeliveryZoneResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_UpdateDeliveryZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deliveryZoneServiceClient) DeleteDeliveryZone(ctx context.Context, in *DeleteDeliveryZoneRequest, opts ...grpc.CallOption) (*DeleteDeliveryZoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDeliveryZoneResponse)
	err := c.cc.Invoke(ctx, DeliveryZoneService_DeleteDeliveryZone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeliveryZoneServiceServer is the server API for DeliveryZoneService service.
// All implementations must embed UnimplementedDeliveryZoneServiceServer
// for forward compatibility.
//
// DeliveryZoneService provides CRUD operations for delivery zones
type DeliveryZoneServiceServer interface {
	// Create a new delivery zone
	CreateDeliveryZone(context.Context, *CreateDeliveryZoneRequest) (*CreateDeliveryZoneResponse, error)
	// Get a delivery zone by ID
	GetDeliveryZone(context.Context, *GetDeliveryZoneRequest) (*GetDeliveryZoneResponse, error)
	// Get a delivery zone by pincode
	GetDeliveryZoneByPincode(context.Context, *GetDeliveryZoneByPincodeRequest) (*GetDeliveryZoneResponse, error)
	// List all delivery zones with pagination
	ListDeliveryZones(context.Context, *ListDeliveryZonesRequest) (*ListDeliveryZonesResponse, error)
	// Update a delivery zone
	UpdateDeliveryZone(context.Context, *UpdateDeliveryZoneRequest) (*UpdateDeliveryZoneResponse, error)
	// Delete a delivery zone
	DeleteDeliveryZone(context.Context, *DeleteDeliveryZoneRequest) (*DeleteDeliveryZoneResponse, error)
	mustEmbedUnimplementedDeliveryZoneServiceServer()
}

// UnimplementedDeliveryZoneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeliveryZoneServiceServer struct{}

func (UnimplementedDeliveryZoneServiceServer) CreateDeliveryZone(context.Context, *CreateDeliveryZoneRequest) (*CreateDeliveryZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDeliveryZone not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) GetDeliveryZone(context.Context, *GetDeliveryZoneRequest) (*GetDeliveryZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryZone not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) GetDeliveryZoneByPincode(context.Context, *GetDeliveryZoneByPincodeRequest) (*GetDeliveryZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeliveryZoneByPincode not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) ListDeliveryZones(context.Context, *ListDeliveryZonesRequest) (*ListDeliveryZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeliveryZones not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) UpdateDeliveryZone(context.Context, *UpdateDeliveryZoneRequest) (*UpdateDeliveryZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeliveryZone not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) DeleteDeliveryZone(context.Context, *DeleteDeliveryZoneRequest) (*DeleteDeliveryZoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDeliveryZone not implemented")
}
func (UnimplementedDeliveryZoneServiceServer) mustEmbedUnimplementedDeliveryZoneServiceServer() {}
func (UnimplementedDeliveryZoneServiceServer) testEmbeddedByValue()                             {}

// UnsafeDeliveryZoneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeliveryZoneServiceServer will
// result in compilation errors.
type UnsafeDeliveryZoneServiceServer interface {
	mustEmbedUnimplementedDeliveryZoneServiceServer()
}

func RegisterDeliveryZoneServiceServer(s grpc.ServiceRegistrar, srv DeliveryZoneServiceServer) {
	// If the following call panics, it indicates UnimplementedDeliveryZoneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeliveryZoneService_ServiceDesc, srv)
}

func _DeliveryZoneService_CreateDeliveryZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeliveryZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).CreateDeliveryZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_CreateDeliveryZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).CreateDeliveryZone(ctx, req.(*CreateDeliveryZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryZoneService_GetDeliveryZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).GetDeliveryZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_GetDeliveryZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).GetDeliveryZone(ctx, req.(*GetDeliveryZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryZoneService_GetDeliveryZoneByPincode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveryZoneByPincodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).GetDeliveryZoneByPincode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_GetDeliveryZoneByPincode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).GetDeliveryZoneByPincode(ctx, req.(*GetDeliveryZoneByPincodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryZoneService_ListDeliveryZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeliveryZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).ListDeliveryZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_ListDeliveryZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).ListDeliveryZones(ctx, req.(*ListDeliveryZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryZoneService_UpdateDeliveryZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeliveryZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).UpdateDeliveryZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_UpdateDeliveryZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).UpdateDeliveryZone(ctx, req.(*UpdateDeliveryZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeliveryZoneService_DeleteDeliveryZone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeliveryZoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryZoneServiceServer).DeleteDeliveryZone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeliveryZoneService_DeleteDeliveryZone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryZoneServiceServer).DeleteDeliveryZone(ctx, req.(*DeleteDeliveryZoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeliveryZoneService_ServiceDesc is the grpc.ServiceDesc for DeliveryZoneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeliveryZoneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoptik.DeliveryZoneService",
	HandlerType: (*DeliveryZoneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDeliveryZone",
			Handler:    _DeliveryZoneService_CreateDeliveryZone_Handler,
		},
		{
			MethodName: "GetDeliveryZone",
			Handler:    _DeliveryZoneService_GetDeliveryZone_Handler,
		},
		{
			MethodName: "GetDeliveryZoneByPincode",
			Handler:    _DeliveryZoneService_GetDeliveryZoneByPincode_Handler,
		},
		{
			MethodName: "ListDeliveryZones",
			Handler:    _DeliveryZoneService_ListDeliveryZones_Handler,
		},
		{
			MethodName: "UpdateDeliveryZone",
			Handler:    _DeliveryZoneService_UpdateDeliveryZone_Handler,
		},
		{
			MethodName: "DeleteDeliveryZone",
			Handler:    _DeliveryZoneService_DeleteDeliveryZone_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "delivery_zone.proto",
}
