// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: delivery_zone.proto

package shoptik

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DeliveryZone represents a serviceable delivery area
type DeliveryZone struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pincode        string                 `protobuf:"bytes,2,opt,name=pincode,proto3" json:"pincode,omitempty"`
	City           string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	IsServiceable  bool                   `protobuf:"varint,5,opt,name=is_serviceable,json=isServiceable,proto3" json:"is_serviceable,omitempty"`
	EtaDays        int32                  `protobuf:"varint,6,opt,name=eta_days,json=etaDays,proto3" json:"eta_days,omitempty"`
	DeliveryCharge float64                `protobuf:"fixed64,7,opt,name=delivery_charge,json=deliveryCharge,proto3" json:"delivery_charge,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliveryZone) Reset() {
	*x = DeliveryZone{}
	mi := &file_delivery_zone_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryZone) ProtoMessage() {}

func (x *DeliveryZone) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryZone.ProtoReflect.Descriptor instead.
func (*DeliveryZone) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{0}
}

func (x *DeliveryZone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeliveryZone) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *DeliveryZone) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DeliveryZone) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *DeliveryZone) GetIsServiceable() bool {
	if x != nil {
		return x.IsServiceable
	}
	return false
}

func (x *DeliveryZone) GetEtaDays() int32 {
	if x != nil {
		return x.EtaDays
	}
	return 0
}

func (x *DeliveryZone) GetDeliveryCharge() float64 {
	if x != nil {
		return x.DeliveryCharge
	}
	return 0
}

func (x *DeliveryZone) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// CreateDeliveryZoneRequest
type CreateDeliveryZoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pincode        string                 `protobuf:"bytes,1,opt,name=pincode,proto3" json:"pincode,omitempty"`
	City           string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State          string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	IsServiceable  bool                   `protobuf:"varint,4,opt,name=is_serviceable,json=isServiceable,proto3" json:"is_serviceable,omitempty"`
	EtaDays        int32                  `protobuf:"varint,5,opt,name=eta_days,json=etaDays,proto3" json:"eta_days,omitempty"`
	DeliveryCharge float64                `protobuf:"fixed64,6,opt,name=delivery_charge,json=deliveryCharge,proto3" json:"delivery_charge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDeliveryZoneRequest) Reset() {
	*x = CreateDeliveryZoneRequest{}
	mi := &file_delivery_zone_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryZoneRequest) ProtoMessage() {}

func (x *CreateDeliveryZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateDeliveryZoneRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDeliveryZoneRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

func (x *CreateDeliveryZoneRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateDeliveryZoneRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *CreateDeliveryZoneRequest) GetIsServiceable() bool {
	if x != nil {
		return x.IsServiceable
	}
	return false
}

func (x *CreateDeliveryZoneRequest) GetEtaDays() int32 {
	if x != nil {
		return x.EtaDays
	}
	return 0
}

func (x *CreateDeliveryZoneRequest) GetDeliveryCharge() float64 {
	if x != nil {
		return x.DeliveryCharge
	}
	return 0
}

// CreateDeliveryZoneResponse
type CreateDeliveryZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryZone  *DeliveryZone          `protobuf:"bytes,1,opt,name=delivery_zone,json=deliveryZone,proto3" json:"delivery_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeliveryZoneResponse) Reset() {
	*x = CreateDeliveryZoneResponse{}
	mi := &file_delivery_zone_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeliveryZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeliveryZoneResponse) ProtoMessage() {}

func (x *CreateDeliveryZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeliveryZoneResponse.ProtoReflect.Descriptor instead.
func (*CreateDeliveryZoneResponse) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDeliveryZoneResponse) GetDeliveryZone() *DeliveryZone {
	if x != nil {
		return x.DeliveryZone
	}
	return nil
}

// GetDeliveryZoneRequest
type GetDeliveryZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryZoneRequest) Reset() {
	*x = GetDeliveryZoneRequest{}
	mi := &file_delivery_zone_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryZoneRequest) ProtoMessage() {}

func (x *GetDeliveryZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryZoneRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryZoneRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetDeliveryZoneResponse
type GetDeliveryZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryZone  *DeliveryZone          `protobuf:"bytes,1,opt,name=delivery_zone,json=deliveryZone,proto3" json:"delivery_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryZoneResponse) Reset() {
	*x = GetDeliveryZoneResponse{}
	mi := &file_delivery_zone_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryZoneResponse) ProtoMessage() {}

func (x *GetDeliveryZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryZoneResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryZoneResponse) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryZoneResponse) GetDeliveryZone() *DeliveryZone {
	if x != nil {
		return x.DeliveryZone
	}
	return nil
}

// GetDeliveryZoneByPincodeRequest
type GetDeliveryZoneByPincodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pincode       string                 `protobuf:"bytes,1,opt,name=pincode,proto3" json:"pincode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryZoneByPincodeRequest) Reset() {
	*x = GetDeliveryZoneByPincodeRequest{}
	mi := &file_delivery_zone_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryZoneByPincodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryZoneByPincodeRequest) ProtoMessage() {}

func (x *GetDeliveryZoneByPincodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryZoneByPincodeRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryZoneByPincodeRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{5}
}

func (x *GetDeliveryZoneByPincodeRequest) GetPincode() string {
	if x != nil {
		return x.Pincode
	}
	return ""
}

// ListDeliveryZonesRequest
type ListDeliveryZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryZonesRequest) Reset() {
	*x = ListDeliveryZonesRequest{}
	mi := &file_delivery_zone_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryZonesRequest) ProtoMessage() {}

func (x *ListDeliveryZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryZonesRequest.ProtoReflect.Descriptor instead.
func (*ListDeliveryZonesRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeliveryZonesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeliveryZonesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// ListDeliveryZonesResponse
type ListDeliveryZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryZones []*DeliveryZone        `protobuf:"bytes,1,rep,name=delivery_zones,json=deliveryZones,proto3" json:"delivery_zones,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeliveryZonesResponse) Reset() {
	*x = ListDeliveryZonesResponse{}
	mi := &file_delivery_zone_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeliveryZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeliveryZonesResponse) ProtoMessage() {}

func (x *ListDeliveryZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeliveryZonesResponse.ProtoReflect.Descriptor instead.
func (*ListDeliveryZonesResponse) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{7}
}

func (x *ListDeliveryZonesResponse) GetDeliveryZones() []*DeliveryZone {
	if x != nil {
		return x.DeliveryZones
	}
	return nil
}

func (x *ListDeliveryZonesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListDeliveryZonesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDeliveryZonesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// UpdateDeliveryZoneRequest
type UpdateDeliveryZoneRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pincode        *string                `protobuf:"bytes,2,opt,name=pincode,proto3,oneof" json:"pincode,omitempty"`
	City           *string                `protobuf:"bytes,3,opt,name=city,proto3,oneof" json:"city,omitempty"`
	State          *string                `protobuf:"bytes,4,opt,name=state,proto3,oneof" json:"state,omitempty"`
	IsServiceable  *bool                  `protobuf:"varint,5,opt,name=is_serviceable,json=isServiceable,proto3,oneof" json:"is_serviceable,omitempty"`
	EtaDays        *int32                 `protobuf:"varint,6,opt,name=eta_days,json=etaDays,proto3,oneof" json:"eta_days,omitempty"`
	DeliveryCharge *float64               `protobuf:"fixed64,7,opt,name=delivery_charge,json=deliveryCharge,proto3,oneof" json:"delivery_charge,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateDeliveryZoneRequest) Reset() {
	*x = UpdateDeliveryZoneRequest{}
	mi := &file_delivery_zone_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryZoneRequest) ProtoMessage() {}

func (x *UpdateDeliveryZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryZoneRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryZoneRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDeliveryZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDeliveryZoneRequest) GetPincode() string {
	if x != nil && x.Pincode != nil {
		return *x.Pincode
	}
	return ""
}

func (x *UpdateDeliveryZoneRequest) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *UpdateDeliveryZoneRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdateDeliveryZoneRequest) GetIsServiceable() bool {
	if x != nil && x.IsServiceable != nil {
		return *x.IsServiceable
	}
	return false
}

func (x *UpdateDeliveryZoneRequest) GetEtaDays() int32 {
	if x != nil && x.EtaDays != nil {
		return *x.EtaDays
	}
	return 0
}

func (x *UpdateDeliveryZoneRequest) GetDeliveryCharge() float64 {
	if x != nil && x.DeliveryCharge != nil {
		return *x.DeliveryCharge
	}
	return 0
}

// UpdateDeliveryZoneResponse
type UpdateDeliveryZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryZone  *DeliveryZone          `protobuf:"bytes,1,opt,name=delivery_zone,json=deliveryZone,proto3" json:"delivery_zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeliveryZoneResponse) Reset() {
	*x = UpdateDeliveryZoneResponse{}
	mi := &file_delivery_zone_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeliveryZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeliveryZoneResponse) ProtoMessage() {}

func (x *UpdateDeliveryZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeliveryZoneResponse.ProtoReflect.Descriptor instead.
func (*UpdateDeliveryZoneResponse) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDeliveryZoneResponse) GetDeliveryZone() *DeliveryZone {
	if x != nil {
		return x.DeliveryZone
	}
	return nil
}

// DeleteDeliveryZoneRequest
type DeleteDeliveryZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeliveryZoneRequest) Reset() {
	*x = DeleteDeliveryZoneRequest{}
	mi := &file_delivery_zone_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeliveryZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeliveryZoneRequest) ProtoMessage() {}

func (x *DeleteDeliveryZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeliveryZoneRequest.ProtoReflect.Descriptor instead.
func (*DeleteDeliveryZoneRequest) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDeliveryZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteDeliveryZoneResponse
type DeleteDeliveryZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDeliveryZoneResponse) Reset() {
	*x = DeleteDeliveryZoneResponse{}
	mi := &file_delivery_zone_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDeliveryZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDeliveryZoneResponse) ProtoMessage() {}

func (x *DeleteDeliveryZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_delivery_zone_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDeliveryZoneResponse.ProtoReflect.Descriptor instead.
func (*DeleteDeliveryZoneResponse) Descriptor() ([]byte, []int) {
	return file_delivery_zone_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDeliveryZoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_delivery_zone_proto protoreflect.FileDescriptor

const file_delivery_zone_proto_rawDesc = "" +
	"\n" +
	"\x13delivery_zone.proto\x12\ashoptik\"\xec\x01\n" +
	"\fDeliveryZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apincode\x18\x02 \x01(\tR\apincode\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12%\n" +
	"\x0eis_serviceable\x18\x05 \x01(\bR\risServiceable\x12\x19\n" +
	"\beta_days\x18\x06 \x01(\x05R\aetaDays\x12'\n" +
	"\x0fdelivery_charge\x18\a \x01(\x01R\x0edeliveryCharge\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\xca\x01\n" +
	"\x19CreateDeliveryZoneRequest\x12\x18\n" +
	"\apincode\x18\x01 \x01(\tR\apincode\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12%\n" +
	"\x0eis_serviceable\x18\x04 \x01(\bR\risServiceable\x12\x19\n" +
	"\beta_days\x18\x05 \x01(\x05R\aetaDays\x12'\n" +
	"\x0fdelivery_charge\x18\x06 \x01(\x01R\x0edeliveryCharge\"X\n" +
	"\x1aCreateDeliveryZoneResponse\x12:\n" +
	"\rdelivery_zone\x18\x01 \x01(\v2\x15.shoptik.DeliveryZoneR\fdeliveryZone\"(\n" +
	"\x16GetDeliveryZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x17GetDeliveryZoneResponse\x12:\n" +
	"\rdelivery_zone\x18\x01 \x01(\v2\x15.shoptik.DeliveryZoneR\fdeliveryZone\";\n" +
	"\x1fGetDeliveryZoneByPincodeRequest\x12\x18\n" +
	"\apincode\x18\x01 \x01(\tR\apincode\"D\n" +
	"\x18ListDeliveryZonesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x99\x01\n" +
	"\x19ListDeliveryZonesResponse\x12<\n" +
	"\x0edelivery_zones\x18\x01 \x03(\v2\x15.shoptik.DeliveryZoneR\rdeliveryZones\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xcb\x02\n" +
	"\x19UpdateDeliveryZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\apincode\x18\x02 \x01(\tH\x00R\apincode\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\x03 \x01(\tH\x01R\x04city\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\x04 \x01(\tH\x02R\x05state\x88\x01\x01\x12*\n" +
	"\x0eis_serviceable\x18\x05 \x01(\bH\x03R\risServiceable\x88\x01\x01\x12\x1e\n" +
	"\beta_days\x18\x06 \x01(\x05H\x04R\aetaDays\x88\x01\x01\x12,\n" +
	"\x0fdelivery_charge\x18\a \x01(\x01H\x05R\x0edeliveryCharge\x88\x01\x01B\n" +
	"\n" +
	"\b_pincodeB\a\n" +
	"\x05_cityB\b\n" +
	"\x06_stateB\x11\n" +
	"\x0f_is_serviceableB\v\n" +
	"\t_eta_daysB\x12\n" +
	"\x10_delivery_charge\"X\n" +
	"\x1aUpdateDeliveryZoneResponse\x12:\n" +
	"\rdelivery_zone\x18\x01 \x01(\v2\x15.shoptik.DeliveryZoneR\fdeliveryZone\"+\n" +
	"\x19DeleteDeliveryZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x1aDeleteDeliveryZoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcc\x04\n" +
	"\x13DeliveryZoneService\x12]\n" +
	"\x12CreateDeliveryZone\x12\".shoptik.CreateDeliveryZoneRequest\x1a#.shoptik.CreateDeliveryZoneResponse\x12T\n" +
	"\x0fGetDeliveryZone\x12\x1f.shoptik.GetDeliveryZoneRequest\x1a .shoptik.GetDeliveryZoneResponse\x12f\n" +
	"\x18GetDeliveryZoneByPincode\x12(.shoptik.GetDeliveryZoneByPincodeRequest\x1a .shoptik.GetDeliveryZoneResponse\x12Z\n" +
	"\x11ListDeliveryZones\x12!.shoptik.ListDeliveryZonesRequest\x1a\".shoptik.ListDeliveryZonesResponse\x12]\n" +
	"\x12UpdateDeliveryZone\x12\".shoptik.UpdateDeliveryZoneRequest\x1a#.shoptik.UpdateDeliveryZoneResponse\x12]\n" +
	"\x12DeleteDeliveryZone\x12\".shoptik.DeleteDeliveryZoneRequest\x1a#.shoptik.DeleteDeliveryZoneResponseB1Z/github.com/shoptik/go-service/pkg/proto/shoptikb\x06proto3"

var (
	file_delivery_zone_proto_rawDescOnce sync.Once
	file_delivery_zone_proto_rawDescData []byte
)

func file_delivery_zone_proto_rawDescGZIP() []byte {
	file_delivery_zone_proto_rawDescOnce.Do(func() {
		file_delivery_zone_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_delivery_zone_proto_rawDesc), len(file_delivery_zone_proto_rawDesc)))
	})
	return file_delivery_zone_proto_rawDescData
}

var file_delivery_zone_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_delivery_zone_proto_goTypes = []any{
	(*DeliveryZone)(nil),                    // 0: shoptik.DeliveryZone
	(*CreateDeliveryZoneRequest)(nil),       // 1: shoptik.CreateDeliveryZoneRequest
	(*CreateDeliveryZoneResponse)(nil),      // 2: shoptik.CreateDeliveryZoneResponse
	(*GetDeliveryZoneRequest)(nil),          // 3: shoptik.GetDeliveryZoneRequest
	(*GetDeliveryZoneResponse)(nil),         // 4: shoptik.GetDeliveryZoneResponse
	(*GetDeliveryZoneByPincodeRequest)(nil), // 5: shoptik.GetDeliveryZoneByPincodeRequest
	(*ListDeliveryZonesRequest)(nil),        // 6: shoptik.ListDeliveryZonesRequest
	(*ListDeliveryZonesResponse)(nil),       // 7: shoptik.ListDeliveryZonesResponse
	(*UpdateDeliveryZoneRequest)(nil),       // 8: shoptik.UpdateDeliveryZoneRequest
	(*UpdateDeliveryZoneResponse)(nil),      // 9: shoptik.UpdateDeliveryZoneResponse
	(*DeleteDeliveryZoneRequest)(nil),       // 10: shoptik.DeleteDeliveryZoneRequest
	(*DeleteDeliveryZoneResponse)(nil),      // 11: shoptik.DeleteDeliveryZoneResponse
}
var file_delivery_zone_proto_depIdxs = []int32{
	0,  // 0: shoptik.CreateDeliveryZoneResponse.delivery_zone:type_name -> shoptik.DeliveryZone
	0,  // 1: shoptik.GetDeliveryZoneResponse.delivery_zone:type_name -> shoptik.DeliveryZone
	0,  // 2: shoptik.ListDeliveryZonesResponse.delivery_zones:type_name -> shoptik.DeliveryZone
	0,  // 3: shoptik.UpdateDeliveryZoneResponse.delivery_zone:type_name -> shoptik.DeliveryZone
	1,  // 4: shoptik.DeliveryZoneService.CreateDeliveryZone:input_type -> shoptik.CreateDeliveryZoneRequest
	3,  // 5: shoptik.DeliveryZoneService.GetDeliveryZone:input_type -> shoptik.GetDeliveryZoneRequest
	5,  // 6: shoptik.DeliveryZoneService.GetDeliveryZoneByPincode:input_type -> shoptik.GetDeliveryZoneByPincodeRequest
	6,  // 7: shoptik.DeliveryZoneService.ListDeliveryZones:input_type -> shoptik.ListDeliveryZonesRequest
	8,  // 8: shoptik.DeliveryZoneService.UpdateDeliveryZone:input_type -> shoptik.UpdateDeliveryZoneRequest
	10, // 9: shoptik.DeliveryZoneService.DeleteDeliveryZone:input_type -> shoptik.DeleteDeliveryZoneRequest
	2,  // 10: shoptik.DeliveryZoneService.CreateDeliveryZone:output_type -> shoptik.CreateDeliveryZoneResponse
	4,  // 11: shoptik.DeliveryZoneService.GetDeliveryZone:output_type -> shoptik.GetDeliveryZoneResponse
	4,  // 12: shoptik.DeliveryZoneService.GetDeliveryZoneByPincode:output_type -> shoptik.GetDeliveryZoneResponse
	7,  // 13: shoptik.DeliveryZoneService.ListDeliveryZones:output_type -> shoptik.ListDeliveryZonesResponse
	9,  // 14: shoptik.DeliveryZoneService.UpdateDeliveryZone:output_type -> shoptik.UpdateDeliveryZoneResponse
	11, // 15: shoptik.DeliveryZoneService.DeleteDeliveryZone:output_type -> shoptik.DeleteDeliveryZoneResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_delivery_zone_proto_init() }
func file_delivery_zone_proto_init() {
	if File_delivery_zone_proto != nil {
		return
	}
	file_delivery_zone_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_delivery_zone_proto_rawDesc), len(file_delivery_zone_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_delivery_zone_proto_goTypes,
		DependencyIndexes: file_delivery_zone_proto_depIdxs,
		MessageInfos:      file_delivery_zone_proto_msgTypes,
	}.Build()
	File_delivery_zone_proto = out.File
	file_delivery_zone_proto_goTypes = nil
	file_delivery_zone_proto_depIdxs = nil
}
