// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: packages/proto/order_log.proto

package shoptik

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderLog represents a log entry for order events
type OrderLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     string                 `protobuf:"bytes,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderLog) Reset() {
	*x = OrderLog{}
	mi := &file_packages_proto_order_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLog) ProtoMessage() {}

func (x *OrderLog) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLog.ProtoReflect.Descriptor instead.
func (*OrderLog) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{0}
}

func (x *OrderLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderLog) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderLog) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderLog) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OrderLog) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *OrderLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OrderLog) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *OrderLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *OrderLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// GetOrderLogsRequest - Get logs for an order
type GetOrderLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLogsRequest) Reset() {
	*x = GetOrderLogsRequest{}
	mi := &file_packages_proto_order_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLogsRequest) ProtoMessage() {}

func (x *GetOrderLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLogsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderLogsRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderLogsRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GetOrderLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetOrderLogsResponse - Paginated order logs
type GetOrderLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*OrderLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLogsResponse) Reset() {
	*x = GetOrderLogsResponse{}
	mi := &file_packages_proto_order_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLogsResponse) ProtoMessage() {}

func (x *GetOrderLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLogsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderLogsResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderLogsResponse) GetLogs() []*OrderLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetOrderLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetOrderLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetOrderLogsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetAllOrderLogsRequest - Get all logs (admin view)
type GetAllOrderLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // Optional filter by event type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrderLogsRequest) Reset() {
	*x = GetAllOrderLogsRequest{}
	mi := &file_packages_proto_order_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrderLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrderLogsRequest) ProtoMessage() {}

func (x *GetAllOrderLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrderLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAllOrderLogsRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllOrderLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllOrderLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllOrderLogsRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

// GetAllOrderLogsResponse
type GetAllOrderLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*OrderLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllOrderLogsResponse) Reset() {
	*x = GetAllOrderLogsResponse{}
	mi := &file_packages_proto_order_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllOrderLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllOrderLogsResponse) ProtoMessage() {}

func (x *GetAllOrderLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllOrderLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAllOrderLogsResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllOrderLogsResponse) GetLogs() []*OrderLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetAllOrderLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetAllOrderLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllOrderLogsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetRecentLogsRequest - Get recent logs for terminal view
type GetRecentLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"` // Number of recent logs to fetch
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentLogsRequest) Reset() {
	*x = GetRecentLogsRequest{}
	mi := &file_packages_proto_order_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLogsRequest) ProtoMessage() {}

func (x *GetRecentLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLogsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentLogsRequest) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{5}
}

func (x *GetRecentLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetRecentLogsResponse
type GetRecentLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*OrderLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentLogsResponse) Reset() {
	*x = GetRecentLogsResponse{}
	mi := &file_packages_proto_order_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentLogsResponse) ProtoMessage() {}

func (x *GetRecentLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_proto_order_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentLogsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentLogsResponse) Descriptor() ([]byte, []int) {
	return file_packages_proto_order_log_proto_rawDescGZIP(), []int{6}
}

func (x *GetRecentLogsResponse) GetLogs() []*OrderLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_packages_proto_order_log_proto protoreflect.FileDescriptor

const file_packages_proto_order_log_proto_rawDesc = "" +
	"\n" +
	"\x1epackages/proto/order_log.proto\x12\ashoptik\"\xd4\x02\n" +
	"\bOrderLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12;\n" +
	"\bmetadata\x18\a \x03(\v2\x1f.shoptik.OrderLog.MetadataEntryR\bmetadata\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Z\n" +
	"\x13GetOrderLogsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"}\n" +
	"\x14GetOrderLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.shoptik.OrderLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"a\n" +
	"\x16GetAllOrderLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\"\x80\x01\n" +
	"\x17GetAllOrderLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.shoptik.OrderLogR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\",\n" +
	"\x14GetRecentLogsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\">\n" +
	"\x15GetRecentLogsResponse\x12%\n" +
	"\x04logs\x18\x01 \x03(\v2\x11.shoptik.OrderLogR\x04logs2\x84\x02\n" +
	"\x0fOrderLogService\x12K\n" +
	"\fGetOrderLogs\x12\x1c.shoptik.GetOrderLogsRequest\x1a\x1d.shoptik.GetOrderLogsResponse\x12T\n" +
	"\x0fGetAllOrderLogs\x12\x1f.shoptik.GetAllOrderLogsRequest\x1a .shoptik.GetAllOrderLogsResponse\x12N\n" +
	"\rGetRecentLogs\x12\x1d.shoptik.GetRecentLogsRequest\x1a\x1e.shoptik.GetRecentLogsResponseB1Z/github.com/shoptik/go-service/pkg/proto/shoptikb\x06proto3"

var (
	file_packages_proto_order_log_proto_rawDescOnce sync.Once
	file_packages_proto_order_log_proto_rawDescData []byte
)

func file_packages_proto_order_log_proto_rawDescGZIP() []byte {
	file_packages_proto_order_log_proto_rawDescOnce.Do(func() {
		file_packages_proto_order_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_proto_order_log_proto_rawDesc), len(file_packages_proto_order_log_proto_rawDesc)))
	})
	return file_packages_proto_order_log_proto_rawDescData
}

var file_packages_proto_order_log_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_packages_proto_order_log_proto_goTypes = []any{
	(*OrderLog)(nil),                // 0: shoptik.OrderLog
	(*GetOrderLogsRequest)(nil),     // 1: shoptik.GetOrderLogsRequest
	(*GetOrderLogsResponse)(nil),    // 2: shoptik.GetOrderLogsResponse
	(*GetAllOrderLogsRequest)(nil),  // 3: shoptik.GetAllOrderLogsRequest
	(*GetAllOrderLogsResponse)(nil), // 4: shoptik.GetAllOrderLogsResponse
	(*GetRecentLogsRequest)(nil),    // 5: shoptik.GetRecentLogsRequest
	(*GetRecentLogsResponse)(nil),   // 6: shoptik.GetRecentLogsResponse
	nil,                             // 7: shoptik.OrderLog.MetadataEntry
}
var file_packages_proto_order_log_proto_depIdxs = []int32{
	7, // 0: shoptik.OrderLog.metadata:type_name -> shoptik.OrderLog.MetadataEntry
	0, // 1: shoptik.GetOrderLogsResponse.logs:type_name -> shoptik.OrderLog
	0, // 2: shoptik.GetAllOrderLogsResponse.logs:type_name -> shoptik.OrderLog
	0, // 3: shoptik.GetRecentLogsResponse.logs:type_name -> shoptik.OrderLog
	1, // 4: shoptik.OrderLogService.GetOrderLogs:input_type -> shoptik.GetOrderLogsRequest
	3, // 5: shoptik.OrderLogService.GetAllOrderLogs:input_type -> shoptik.GetAllOrderLogsRequest
	5, // 6: shoptik.OrderLogService.GetRecentLogs:input_type -> shoptik.GetRecentLogsRequest
	2, // 7: shoptik.OrderLogService.GetOrderLogs:output_type -> shoptik.GetOrderLogsResponse
	4, // 8: shoptik.OrderLogService.GetAllOrderLogs:output_type -> shoptik.GetAllOrderLogsResponse
	6, // 9: shoptik.OrderLogService.GetRecentLogs:output_type -> shoptik.GetRecentLogsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_packages_proto_order_log_proto_init() }
func file_packages_proto_order_log_proto_init() {
	if File_packages_proto_order_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_proto_order_log_proto_rawDesc), len(file_packages_proto_order_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_proto_order_log_proto_goTypes,
		DependencyIndexes: file_packages_proto_order_log_proto_depIdxs,
		MessageInfos:      file_packages_proto_order_log_proto_msgTypes,
	}.Build()
	File_packages_proto_order_log_proto = out.File
	file_packages_proto_order_log_proto_goTypes = nil
	file_packages_proto_order_log_proto_depIdxs = nil
}
