// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: packages/proto/order_log.proto

package shoptik

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderLogService_GetOrderLogs_FullMethodName    = "/shoptik.OrderLogService/GetOrderLogs"
	OrderLogService_GetAllOrderLogs_FullMethodName = "/shoptik.OrderLogService/GetAllOrderLogs"
	OrderLogService_GetRecentLogs_FullMethodName   = "/shoptik.OrderLogService/GetRecentLogs"
)

// OrderLogServiceClient is the client API for OrderLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderLogService provides access to order event logs
type OrderLogServiceClient interface {
	// Get logs for a specific order
	GetOrderLogs(ctx context.Context, in *GetOrderLogsRequest, opts ...grpc.CallOption) (*GetOrderLogsResponse, error)
	// Get all logs with pagination (admin)
	GetAllOrderLogs(ctx context.Context, in *GetAllOrderLogsRequest, opts ...grpc.CallOption) (*GetAllOrderLogsResponse, error)
	// Get recent logs for real-time terminal view
	GetRecentLogs(ctx context.Context, in *GetRecentLogsRequest, opts ...grpc.CallOption) (*GetRecentLogsResponse, error)
}

type orderLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderLogServiceClient(cc grpc.ClientConnInterface) OrderLogServiceClient {
	return &orderLogServiceClient{cc}
}

func (c *orderLogServiceClient) GetOrderLogs(ctx context.Context, in *GetOrderLogsRequest, opts ...grpc.CallOption) (*GetOrderLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderLogsResponse)
	err := c.cc.Invoke(ctx, OrderLogService_GetOrderLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderLogServiceClient) GetAllOrderLogs(ctx context.Context, in *GetAllOrderLogsRequest, opts ...grpc.CallOption) (*GetAllOrderLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllOrderLogsResponse)
	err := c.cc.Invoke(ctx, OrderLogService_GetAllOrderLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderLogServiceClient) GetRecentLogs(ctx context.Context, in *GetRecentLogsRequest, opts ...grpc.CallOption) (*GetRecentLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecentLogsResponse)
	err := c.cc.Invoke(ctx, OrderLogService_GetRecentLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderLogServiceServer is the server API for OrderLogService service.
// All implementations must embed UnimplementedOrderLogServiceServer
// for forward compatibility.
//
// OrderLogService provides access to order event logs
type OrderLogServiceServer interface {
	// Get logs for a specific order
	GetOrderLogs(context.Context, *GetOrderLogsRequest) (*GetOrderLogsResponse, error)
	// Get all logs with pagination (admin)
	GetAllOrderLogs(context.Context, *GetAllOrderLogsRequest) (*GetAllOrderLogsResponse, error)
	// Get recent logs for real-time terminal view
	GetRecentLogs(context.Context, *GetRecentLogsRequest) (*GetRecentLogsResponse, error)
	mustEmbedUnimplementedOrderLogServiceServer()
}

// UnimplementedOrderLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderLogServiceServer struct{}

func (UnimplementedOrderLogServiceServer) GetOrderLogs(context.Context, *GetOrderLogsRequest) (*GetOrderLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderLogs not implemented")
}
func (UnimplementedOrderLogServiceServer) GetAllOrderLogs(context.Context, *GetAllOrderLogsRequest) (*GetAllOrderLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllOrderLogs not implemented")
}
func (UnimplementedOrderLogServiceServer) GetRecentLogs(context.Context, *GetRecentLogsRequest) (*GetRecentLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentLogs not implemented")
}
func (UnimplementedOrderLogServiceServer) mustEmbedUnimplementedOrderLogServiceServer() {}
func (UnimplementedOrderLogServiceServer) testEmbeddedByValue()                         {}

// UnsafeOrderLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderLogServiceServer will
// result in compilation errors.
type UnsafeOrderLogServiceServer interface {
	mustEmbedUnimplementedOrderLogServiceServer()
}

func RegisterOrderLogServiceServer(s grpc.ServiceRegistrar, srv OrderLogServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderLogService_ServiceDesc, srv)
}

func _OrderLogService_GetOrderLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderLogServiceServer).GetOrderLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderLogService_GetOrderLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderLogServiceServer).GetOrderLogs(ctx, req.(*GetOrderLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderLogService_GetAllOrderLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllOrderLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderLogServiceServer).GetAllOrderLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderLogService_GetAllOrderLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderLogServiceServer).GetAllOrderLogs(ctx, req.(*GetAllOrderLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderLogService_GetRecentLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderLogServiceServer).GetRecentLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderLogService_GetRecentLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderLogServiceServer).GetRecentLogs(ctx, req.(*GetRecentLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderLogService_ServiceDesc is the grpc.ServiceDesc for OrderLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shoptik.OrderLogService",
	HandlerType: (*OrderLogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderLogs",
			Handler:    _OrderLogService_GetOrderLogs_Handler,
		},
		{
			MethodName: "GetAllOrderLogs",
			Handler:    _OrderLogService_GetAllOrderLogs_Handler,
		},
		{
			MethodName: "GetRecentLogs",
			Handler:    _OrderLogService_GetRecentLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packages/proto/order_log.proto",
}
