apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
  namespace: shoptik
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: shoptik
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXT_PUBLIC_API_URL: "http://nestjs-service:5001"
