apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shoptik

resources:
  - namespace/namespace.yaml
  - secrets/secrets.yaml
  - storage/storage.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/configmap.yaml
  - postgres/migration-job.yaml
  - mongodb/statefulset.yaml
  - mongodb/service.yaml
  - redis/statefulset.yaml
  - redis/service.yaml
