apiVersion: v1
kind: ConfigMap
metadata:
  name: go-config
  namespace: shoptik
  labels:
    app.kubernetes.io/name: go-service
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: shoptik
data:
  GO_ENV: "production"
  HTTP_PORT: "5002"
  GRPC_PORT: "5003"
