apiVersion: v1
kind: Service
metadata:
  name: go-service
  namespace: shoptik
  labels:
    app.kubernetes.io/name: go-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: shoptik
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
    - port: 5003
      targetPort: 5003
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: go-service
